### ISSUE TITLE
ServerlessError: Export 'project-name-ServerlessAliasReference' does not exist.

### ISSUE THREAD

**Issue by sorash** [serverless-heaven/serverless-aws-alias#181]
I am seeing the following error message when using serverless@1.61.3. This issue does not happen with prior versions.
```
Serverless: [AWS cloudformation 400 0.279s 0 retries] listImports({ ExportName: 'project-name-ServerlessAliasReference' })

Serverless Error ---------------------------------------

ServerlessError: Export 'project-name-ServerlessAliasReference' does not exist.
    at promise.catch.err (C:\Users\user\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:329:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Environment:
```
Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.16.0
     Framework Version:         1.61.3
     Plugin Version:            3.2.7
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

Looking into the changelog for 1.61.3, [this commit](https://github.com/serverless/serverless/commit/f1cc3a899856a12ed251ea4a0947a331861cd8b3) seems to try and improve error handling, which could be causing this message to come up.

Temporary fix to this problem for anyone else running into it, is to install version 1.61.2 as a project dev dependency and use `node ./node_modules/serverless/bin/serverless deploy` instead.

Please let me know if any more information can help.

**Comment by shintasmith** [comment]
I am seeing this issue with version `1.62` as well. Downgrading to serverless version `1.61.2` solves the problem . But it would be good to have this fixed in the latest version so we don't have to keep pinning on version `1.61.2`.

**Comment by raymercb** [comment]
Hi guys, any update on this? I'm getting the same message with serverless **1.66.0**.

**Comment by victoraldir** [comment]
Hello folks, the problem seems to be happening with **1.67.0** as well

> Framework Core: 1.67.0
> Plugin: 3.5.0
> SDK: 2.3.0
> Components: 2.22.3

Any updates?

**Comment by Enase** [comment]
fix is coming https://github.com/serverless-heaven/serverless-aws-alias/pull/186

**Comment by raymercb** [comment]
Meanwhile, to avoid this error, we can downgrade the serverless version. This one works well on my side: **1.61.2**

**Comment by siovaneDAZN** [comment]
Same problem with 1.78.1. Has the problem been fixed?

**Comment by brotodex** [comment]
Still experiencing the same issue. Is there any plan on fixing this? Thanks!

**Comment by PaulKleinschmidt** [comment]
Experiencing this problem with 1.80.0. Any updates on this being fixed?

**Comment by dobeerman7** [comment]
Still persists on 2.3.0

**Comment by tanmay-kulkarni** [comment]
User with version 2.9.0 here. This issue is still there. As this is so far beyond version 1.61.2, I kinda don't want to downgrade as suggested above. Would be great if this issue is fixed soon. Thank you.

**Comment by eliyasmeth** [comment]
Any updates on this being fixed? I really needs this and I can't find an alternative or workaround.

**Comment by eliyasmeth** [comment]
> fix is coming #186

I can confirm this is working, one more review is pending on the PR.
Using serverless 2.11.1

**Comment by StealthyDev** [comment]
Is the fix released? Here is what I'm on:

serverless v2.15.0
serverless-aws-alias v1.8.0

**Comment by thomasfaller** [comment]
Same issue with the following:

Serverless: 2.18.0
serverless-aws-alias: 1.8.0

**Comment by Enase** [comment]
Quick fix can be found [here](https://github.com/serverless-heaven/serverless-aws-alias/pull/186#issuecomment-757138441)

**Comment by danieljosephbrennan** [comment]
Same issue with

Serverless: 2.29
serverless-aws-alias: 1.8.0

Same issue with the serverless-aws-alias-fixed package

**Comment by kennrll18** [comment]
The only way i got this to work is to use this
"serverless": "1.61.2",
"serverless-aws-alias": "^1.8.0",
"serverless-aws-alias-alb-patch": "^1.1.0",

or you can use the following without serverless-aws-alias
"serverless": "2.11.1",
"serverless-aws-alias-fixed": "^2.0.1",

**Comment by ABRAJ11** [comment]
It worked for me when i used  following changes:


# file : package.json  
"devDependencies": {
                "serverless-aws-alias-fixed": "^2.0.1"
    }

#############################
# On file : serverless.yaml 
 ................... 
  plugins:
  - serverless-aws-alias-fixed

**Comment by peebles** [comment]
"serverless": "^2.60.0",
    "serverless-aws-alias-fixed": "^2.0.1",

fails.

```
...
Serverless: Deprecation warnings:
Detected unrecognized CLI options: "--alias", "--retain".
Starting with the next major, Serverless Framework will report them with a thrown error
...
Serverless Error ----------------------------------------
 
  ServerlessError: Export 're-dev-ServerlessAliasReference' does not exist.
      at /builds/zhor-tech/products/cloud/digital/cloud/rengines/node_modules/serverless/lib/aws/request.js:225:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async persistentRequest (/builds/zhor-tech/products/cloud/digital/cloud/rengines/node_modules/serverless/lib/aws/request.js:149:14)
...
```
