### ISSUE TITLE
TypeError: this.aliasStackGetAliasStackNames(...).mapSeries is not a function

### ISSUE THREAD

**Issue by ammu2705** [serverless-heaven/serverless-aws-alias#213]
Type Error ----------------------------------------------
 
  TypeError: this.aliasStackGetAliasStackNames(...).mapSeries is not a function
      at AwsAlias.aliasStackLoadAliasTemplates (/opt/atlassian/pipelines/agent/build/node_modules/serverless-aws-alias-fixed/lib/stackInformation.js:82:4)
      at AwsAlias.tryCatcher (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.0
     Framework Version:         2.71.0 (local)
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1

**Comment by ammu2705** [comment]
I got this issue when upgraded serverless package v2.71.0. 
Please help to fix the issue with serverless v2.71.0 or v2.70.0

**Comment by cmoreaubetclic** [comment]
Hello, I have the same issue. Did you find any workaround ?
